model_name: "ST-GCN"
in_channels: 4
num_classes: 60
graph_layout: "mediapipe_33"
num_joints: 33
edge_importance_weighting: true
temporal_kernel_size: 9
dropout: 0.5
embedding_dim: 256
channel_list: [64, 64, 64, 128, 128, 128, 256, 256, 256]
